[build]
  command = "yarn install && yarn build"

[build.environment]
  NODE_VERSION = "18.16.0"
  YARN_VERSION = "1.22.19"

[build.processing]
  command = "yarn install && yarn build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
